import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { CartContextProvider } from "@/context/cart-context/cart-context";

const noto_sans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Food Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${noto_sans.className} `}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <CartContextProvider>
            <Header />
            <main className="pb-16">{children}</main>
          </CartContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
